export const polissa = {
  values: {
    ac_state: false,
    active: true,
    agree_dh: "E1",
    agree_tarifa: "2A",
    agree_tensio: "E0",
    agree_tipus: "05",
    altre_p: false,
    autoconsum_id: false,
    autoconsumo: "00",
    bank: false,
    bono_social_disponible: false,
    butlletins: [],
    cnae: [
      3,
      "0111 - Cultivo de cereales (excepto arroz), leguminosas y semillas oleaginosas",
    ],
    codigo_promocional: false,
    coef_repartiment: 0.0,
    comercial_id: false,
    comercialitzadora: [3, "Agrolait"],
    comissio: false,
    comptador: "2222222",
    comptadors: [2],
    condicions_generals_id: false,
    contract_type: "01",
    cups: [2, "ES1234000000000002JJ0F"],
    cups_cp: [],
    cups_direccio: "carrer inventat 1 1 1 2 aclaridor 00001 (Poble de Prova)",
    cups_poblacio: [],
    data_alta: "2016-01-01",
    data_baixa: "2017-01-01",
    data_firma_contracte: "2016-01-01 00:00:00",
    data_ultima_lectura: false,
    data_ultima_lectura_estimada: false,
    debt_amount: 0.0,
    deposit: false,
    direccio_notificacio: [10, "Sylvie Lelitre, 69 rue de Chimay  5478 Wavre"],
    direccio_pagament: [10, "Sylvie Lelitre, 69 rue de Chimay  5478 Wavre"],
    distri_phone: "",
    distribuidora: [2, "ASUStek"],
    enviament: "postal",
    expected_consumption: false,
    facturacio: 1,
    facturacio_distri: false,
    facturacio_endarrerida: true,
    facturacio_potencia: "max",
    facturacio_suspesa: false,
    firmat: true,
    id: 2,
    is_autoconsum_collectiu: false,
    lectura_en_baja: false,
    llista_preu: false,
    log_ids: [2],
    lot_facturacio: [3, "01/2016"],
    modcontractual_activa: false,
    modcontractuals_ids: [],
    mode_facturacio: "atr",
    name: "0002",
    name_auto: true,
    no_cessio_sips: "unactive",
    no_cessio_sips_data: false,
    nocutoff: false,
    notificacio: "titular",
    notificacio_email: false,
    observacions: "Observacio 1.",
    pagador: [3, "Agrolait"],
    pagador_email: false,
    pagador_nif: "ESB83677229",
    pagador_sel: "titular",
    payment_mode_id: false,
    payment_term: false,
    pending_amount: 0.0,
    pending_state: "Correct",
    persona_fisica: "CI",
    potencia: 6.0,
    potencies_periode: [],
    print_observations: false,
    process_id: [1, "Default Process"],
    property_unitat_potencia: [85, "kW/dia"],
    propietari_bank: false,
    proxima_facturacio: "2016-01-31",
    ref_dist: false,
    refacturacio_pendent: false,
    related_attachments: [],
    renovacio_auto: false,
    representante_id: false,
    state: "esborrany",
    state_post_facturacio: false,
    tarifa: [1, "2.0A"],
    tarifa_codi: "2.0A",
    tensio: 127,
    tensio_normalitzada: [1, "127"],
    tg: "1",
    tipo_pago: [1, "Demo payment type"],
    tipus_vivenda: "habitual",
    titular: [4, "Camptocamp"],
    titular_nif: "ESB82420654",
    trafo: false,
    unpaid_invoices: false,
    user_id: [1, "Administrator1"],
    versio_primera_factura: false,
  },
  fields: {
    ac_state: {
      digits: [16, 2],
      readonly: true,
      string: "Estat de l'AC",
      type: "char",
      views: {},
    },
    active: {
      readonly: true,
      required: true,
      string: "Activa",
      type: "boolean",
      views: {},
    },
    agree_dh: {
      digits: [16, 2],
      readonly: 1,
      size: 2,
      string: "Codi DH",
      type: "char",
      views: {},
    },
    agree_tarifa: {
      digits: [16, 2],
      readonly: 1,
      size: 2,
      string: "Codi Tarifa",
      type: "char",
      views: {},
    },
    agree_tensio: {
      digits: [16, 2],
      readonly: 1,
      size: 2,
      string: "Codi Tensió",
      type: "char",
      views: {},
    },
    agree_tipus: {
      digits: [16, 2],
      readonly: 1,
      size: 2,
      string: "Tipus Punt",
      type: "char",
      views: {},
    },
    altre_p: {
      context: "",
      domain: [],
      readonly: true,
      relation: "res.partner",
      size: 40,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Contacte alternatiu",
      type: "many2one",
      views: {},
    },
    autoconsum_id: {
      context: "",
      digits: [16, 2],
      domain: [],
      readonly: true,
      relation: "giscedata.autoconsum",
      string: "Autoconsum",
      type: "many2one",
      views: {},
    },
    autoconsumo: {
      help: "Tipus de autoconsum del contracte segons RD. 900/2015",
      readonly: true,
      selection: [
        ["00", "Sin Autoconsumo"],
        ["01", "Autoconsumo Tipo 1"],
        ["2A", "Autoconsumo tipo 2 (según el Art. 13. 2. a) RD 900/2015)"],
        ["2B", "Autoconsumo tipo 2 (según el Art. 13. 2. b) RD 900/2015)"],
        [
          "2G",
          "Servicios auxiliares de generación ligada a un autoconsumo tipo 2",
        ],
        ["31", "Sin Excedentes Individual – Consumo"],
        ["32", "Sin Excedentes Colectivo – Consumo"],
        [
          "33",
          "Sin Excedentes Colectivo con acuerdo de compensación – Consumo",
        ],
        ["41", "Con excedentes y compensación Individual - Consumo "],
        ["42", "Con excedentes y compensación Colectivo– Consumo"],
        [
          "51",
          "Con excedentes sin compensación Individual sin cto de SSAA en Red Interior– Consumo",
        ],
        [
          "52",
          "Con excedentes sin compensación Colectivo sin cto de SSAA en Red Interior– Consumo",
        ],
        [
          "53",
          "Con excedentes sin compensación Individual con cto SSAA en Red Interior– Consumo",
        ],
        [
          "54",
          "Con excedentes sin compensación individual con cto SSAA en Red Interior– SSAA",
        ],
        [
          "55",
          "Con excedentes sin compensación Colectivo/en Red Interior– Consumo",
        ],
        [
          "56",
          "Con excedentes sin compensación Colectivo/en Red Interior - SSAA",
        ],
        [
          "61",
          "Con excedentes sin compensación Individual con cto SSAA a través de red – Consumo",
        ],
        [
          "62",
          "Con excedentes sin compensación individual con cto SSAA a través de red – SSAA",
        ],
        [
          "63",
          "Con excedentes sin compensación Colectivo a través de red – Consumo",
        ],
        [
          "64",
          "Con excedentes sin compensación Colectivo a través de red - SSAA",
        ],
        [
          "71",
          "Con excedentes sin compensación Individual con cto SSAA a través de red y red interior – Consumo",
        ],
        [
          "72",
          "Con excedentes sin compensación individual con cto SSAA a través de red y red interior – SSAA",
        ],
        [
          "73",
          "Con excedentes sin compensación Colectivo con cto de SSAA  a través de red y red interior – Consumo",
        ],
        [
          "74",
          "Con excedentes sin compensación Colectivo con cto de SSAA a través de red y red interior - SSAA",
        ],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Autoconsum",
      type: "selection",
      views: {},
    },
    bank: {
      context: "",
      domain: [],
      readonly: true,
      relation: "res.partner.bank",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Compte bancari",
      type: "many2one",
      views: {},
    },
    bono_social_disponible: {
      digits: [16, 2],
      readonly: 1,
      string: "Bo social disponible",
      type: "boolean",
      views: {},
    },
    butlletins: {
      context: "",
      digits: [16, 2],
      domain: [],
      relation: "giscedata.butlleti",
      string: "Bulletins",
      type: "one2many",
      views: {},
    },
    cnae: {
      context: "",
      domain: [],
      readonly: true,
      relation: "giscemisc.cnae",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "CNAE",
      type: "many2one",
      views: {},
    },
    codigo_promocional: {
      size: 20,
      string: "Codi promocional",
      type: "char",
      views: {},
    },
    coef_repartiment: {
      digits: [12, 2],
      readonly: true,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Coeficient de repartiment [%]",
      type: "float",
      views: {},
    },
    comercial_id: {
      context: "",
      domain: [],
      relation: "hr.employee",
      size: 64,
      string: "Comercial",
      type: "many2one",
      views: {},
    },
    comissio: {
      selection: [["giscedata.polissa.comissio.unica", "Comissió Única"]],
      size: 256,
      string: "Comissió Asignada",
      type: "reference",
      views: {},
    },
    comptador: {
      digits: [16, 2],
      readonly: 1,
      select: true,
      size: 64,
      string: "Comptador",
      type: "char",
      views: {},
    },
    comptadors: {
      context: {
        active_test: false,
      },
      domain: [],
      inv_field: "polissa",
      relation: "giscedata.lectures.comptador",
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [["readonly", false]],
      },
      string: "Comptadors",
      type: "one2many",
      views: {},
    },
    condicions_generals_id: {
      context: "",
      domain: [],
      relation: "giscedata.polissa.condicions.generals",
      size: 64,
      string: "Condicions generals",
      type: "many2one",
      views: {},
    },
    contract_type: {
      help: "Distintos tipos de contratos. Ver REAL DECRETO 1164/2001",
      readonly: true,
      selection: [
        ["01", "Anual"],
        ["02", "Eventual medido"],
        ["03", "Temporada"],
        ["05", "Suministro Régimen especial"],
        ["07", "Suministro de Obras"],
        ["08", "Suministro de Socorro"],
        ["09", "Eventual a tanto alzado"],
        ["10", "Pruebas"],
        ["11", "Duplicado"],
        ["12", "De reserva"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Tipus de contracte",
      type: "selection",
      views: {},
    },
    cups: {
      context: "",
      domain: [],
      readonly: true,
      relation: "giscedata.cups.ps",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "CUPS",
      type: "many2one",
      views: {},
    },
    cups_cp: {
      digits: [16, 2],
      readonly: 1,
      string: "Codi Postal",
      type: "char",
      views: {},
    },
    cups_direccio: {
      digits: [16, 2],
      readonly: true,
      size: 256,
      string: "Direcció CUPS",
      type: "char",
      views: {},
    },
    cups_poblacio: {
      digits: [16, 2],
      readonly: 1,
      string: "Població",
      type: "char",
      views: {},
    },
    data_alta: {
      readonly: true,
      states: {
        esborrany: [["readonly", false]],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Data alta",
      type: "date",
      views: {},
    },
    data_baixa: {
      string: "Data baixa",
      type: "date",
      views: {},
    },
    data_firma_contracte: {
      readonly: true,
      states: {
        esborrany: [["readonly", false]],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Data firma contracte",
      type: "datetime",
      views: {},
    },
    data_ultima_lectura: {
      digits: [16, 2],
      string: "Data última real facturada",
      type: "date",
      views: {},
    },
    data_ultima_lectura_estimada: {
      string: "Data última estimada facturada",
      type: "date",
      views: {},
    },
    debt_amount: {
      digits: [16, 2],
      readonly: 1,
      string: "Debt amount",
      type: "float",
      views: {},
    },
    deposit: {
      digits: [16, 2],
      readonly: 1,
      string: "Dipòsit",
      type: "float",
      views: {},
    },
    direccio_notificacio: {
      context: "",
      domain: [],
      readonly: true,
      relation: "res.partner.address",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Adreça notificació",
      type: "many2one",
      views: {},
    },
    direccio_pagament: {
      context: "",
      domain: [],
      readonly: true,
      relation: "res.partner.address",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Adreça fiscal",
      type: "many2one",
      views: {},
    },
    distribuidora: {
      context: "",
      domain: [["supplier", "=", 1]],
      readonly: true,
      relation: "res.partner",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Distribuidora",
      type: "many2one",
      views: {},
    },
    enviament: {
      readonly: true,
      selection: [
        ["postal", "Correu postal"],
        ["email", "E-mail"],
        ["postal+email", "Correu postal i e-mail"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [["readonly", false]],
      },
      string: "Enviar factura via",
      type: "selection",
      views: {},
    },
    expected_consumption: {
      help:
        "Aquest camp calcula el consum total pactat per contractes eventuals sense comptador",
      readonly: true,
      string: "Consum pactat",
      type: "float",
      views: {},
    },
    facturacio: {
      readonly: true,
      selection: [
        [1, "Mensual"],
        [2, "Bimestral"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Facturació",
      type: "selection",
      views: {},
    },
    facturacio_distri: {
      help: "Periodicitat de facturació dedistribuidora",
      readonly: true,
      selection: [
        [1, "Mensual"],
        [2, "Bimestral"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Facturació de distribuïdora",
      type: "selection",
      views: {},
    },
    facturacio_potencia: {
      readonly: true,
      selection: [
        ["max", "Maxímetro"],
        ["icp", "ICP"],
        ["recarrec", "Recàrrec ICP"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Facturación Potencia",
      type: "selection",
      views: {},
    },
    facturacio_suspesa: {
      string: "Facturació Suspesa",
      type: "boolean",
      views: {},
    },
    is_autoconsum_collectiu: {
      digits: [16, 2],
      readonly: 1,
      string: "Es col·lectiu",
      type: "boolean",
      views: {},
    },
    lectura_en_baja: {
      readonly: true,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [["readonly", false]],
      },
      string: "Lectura en baixa",
      type: "boolean",
      views: {},
    },
    llista_preu: {
      context: "",
      domain: [["type", "=", "sale"]],
      readonly: true,
      relation: "product.pricelist",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Tarifa Comercialitzadora",
      type: "many2one",
      views: {},
    },
    log_ids: {
      context: "",
      domain: [],
      inv_field: "polissa_id",
      readonly: true,
      relation: "giscedata.polissa.log",
      string: "Històric",
      type: "one2many",
      views: {},
    },
    lot_facturacio: {
      context: "",
      domain: [],
      relation: "giscedata.facturacio.lot",
      size: 64,
      string: "Lot de facturació",
      type: "many2one",
      views: {},
    },
    modcontractual_activa: {
      context: "",
      domain: [],
      readonly: true,
      relation: "giscedata.polissa.modcontractual",
      size: 64,
      string: "Modificació contractual actual",
      type: "many2one",
      views: {},
    },
    modcontractuals_ids: {
      context: {
        active_test: false,
      },
      domain: [],
      inv_field: "polissa_id",
      readonly: true,
      relation: "giscedata.polissa.modcontractual",
      string: "Modificacions contractuals",
      type: "one2many",
      views: {},
    },
    name: {
      readonly: true,
      select: true,
      size: 60,
      states: {
        esborrany: [["readonly", false]],
      },
      string: "Contracte",
      type: "char",
      views: {},
    },
    name_auto: {
      string: "Auto",
      type: "boolean",
      views: {},
    },
    no_cessio_sips: {
      readonly: true,
      selection: [
        ["unactive", "Desactivat"],
        ["requested", "Sol·licitat"],
        ["active", "Activat"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "No cessió de SIPS",
      type: "selection",
      views: {},
    },
    no_cessio_sips_data: {
      readonly: true,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Data sol·licitud",
      type: "date",
      views: {},
    },
    nocutoff: {
      context: "",
      domain: [],
      readonly: true,
      relation: "giscedata.polissa.nocutoff",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Subministrament no tallable",
      type: "many2one",
      views: {},
    },
    notificacio: {
      readonly: true,
      selection: [
        ["titular", "Titular"],
        ["pagador", "Fiscal"],
        ["altre_p", "Altra"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Persona notificació",
      type: "selection",
      views: {},
    },
    notificacio_email: {
      digits: [16, 2],
      readonly: 1,
      size: 240,
      string: "Email dir. notif.",
      type: "char",
      views: {},
    },
    observacions: {
      string: "Observacions",
      type: "text",
      views: {},
    },
    pagador: {
      context: "",
      domain: [],
      readonly: true,
      relation: "res.partner",
      select: true,
      size: 40,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Raó fiscal",
      type: "many2one",
      views: {},
    },
    pagador_email: {
      digits: [16, 2],
      readonly: 1,
      size: 240,
      string: "Email dir. fiscal",
      type: "char",
      views: {},
    },
    pagador_nif: {
      digits: [16, 2],
      readonly: true,
      string: "NIF fiscal",
      type: "char",
      views: {},
    },
    pagador_sel: {
      readonly: true,
      selection: [
        ["titular", "Titular"],
        ["altre_p", "Altre"],
      ],
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Persona fiscal",
      type: "selection",
      views: {},
    },
    payment_mode_id: {
      context: "",
      domain: [],
      readonly: true,
      relation: "payment.mode",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Grup de pagament",
      type: "many2one",
      views: {},
    },
    payment_term: {
      context: "",
      domain: [],
      readonly: true,
      relation: "account.payment.term",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", false],
        ],
        validar: [
          ["readonly", false],
          ["required", false],
        ],
      },
      string: "Plazo de pago",
      type: "many2one",
      views: {},
    },
    pending_amount: {
      digits: [16, 2],
      readonly: 1,
      string: "Pending amount",
      type: "float",
      views: {},
    },
    pending_state: {
      digits: [16, 2],
      readonly: 1,
      size: 64,
      string: "Pending State",
      type: "char",
      views: {},
    },
    persona_fisica: {
      digits: [16, 2],
      size: 2,
      string: "unknown",
      type: "char",
      views: {},
    },
    potencia: {
      digits: [16, 3],
      readonly: true,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Potència contractada (kW)",
      type: "float",
      views: {},
    },
    potencies_periode: {
      context: "",
      domain: [],
      inv_field: "polissa_id",
      readonly: true,
      relation: "giscedata.polissa.potencia.contractada.periode",
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Potencies contractades per periode",
      type: "one2many",
      views: {
        form: {
          arch:
            '<form string="Pot&#xE8;ncia">\n                                        <field name="periode_id" readonly="1"/>\n                                        <field name="potencia"/>\n                                    </form>\n                                ',
          fields: {
            periode_id: {
              context: "",
              domain: [],
              readonly: true,
              relation: "giscedata.polissa.tarifa.periodes",
              required: true,
              size: 64,
              string: "Periode",
              type: "many2one",
              views: {},
            },
            potencia: {
              digits: [15, 3],
              required: true,
              string: "Potencia contractada",
              type: "float",
              views: {},
            },
          },
        },
        tree: {
          arch:
            '<tree string="Pot&#xE8;ncies">\n                                        <field name="periode_id"/>\n                                        <field name="potencia"/>\n                                    </tree>\n                                    ',
          fields: {
            periode_id: {
              context: "",
              domain: [],
              readonly: true,
              relation: "giscedata.polissa.tarifa.periodes",
              required: true,
              size: 64,
              string: "Periode",
              type: "many2one",
              views: {},
            },
            potencia: {
              digits: [15, 3],
              required: true,
              string: "Potencia contractada",
              type: "float",
              views: {},
            },
          },
        },
      },
    },
    print_observations: {
      string: "Observacions impresses",
      type: "text",
      views: {},
    },
    process_id: {
      context: "",
      digits: [16, 2],
      domain: [],
      readonly: true,
      relation: "account.invoice.pending.state.process",
      required: true,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Procés de tall",
      type: "many2one",
      views: {},
    },
    property_unitat_potencia: {
      context: "",
      digits: [16, 2],
      domain: "[('category_id.name', '=', 'POT ELEC')]",
      help: "Amb quina unitat es vol facturar la potència",
      readonly: true,
      relation: "product.uom",
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Unitat de facturació potència",
      type: "many2one",
      views: {},
    },
    propietari_bank: {
      digits: [16, 2],
      readonly: true,
      size: 128,
      string: "Propietari compte bancari",
      type: "char",
      views: {},
    },
    ref_dist: {
      size: 60,
      string: "Referència distribuidora",
      type: "char",
      views: {},
    },
    refacturacio_pendent: {
      string: "Refacturació Pendent",
      type: "boolean",
      views: {},
    },
    related_attachments: {
      context: "",
      digits: [16, 2],
      domain: [],
      readonly: 1,
      relation: "ir.attachment",
      string: "Adjunts relacionats",
      type: "one2many",
      views: {},
    },
    renovacio_auto: {
      string: "Renovació Automàtica",
      type: "boolean",
      views: {},
    },
    representante_id: {
      context: "",
      domain: [],
      readonly: true,
      relation: "res.partner",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Representante",
      type: "many2one",
      views: {},
    },
    state: {
      readonly: true,
      required: true,
      selection: [
        ["esborrany", "Esborrany"],
        ["validar", "Validar"],
        ["pendent", "Pendent"],
        ["activa", "Activa"],
        ["cancelada", "Cancel·lada"],
        ["contracte", "Activació Contracte"],
        ["novapolissa", "Creació nova pòlissa"],
        ["modcontractual", "Modificació Contractual"],
        ["impagament", "Impagament"],
        ["tall", "Tall"],
        ["baixa", "Baixa"],
        ["facturacio", "Facturació"],
      ],
      string: "Estat",
      type: "selection",
      views: {},
    },
    tarifa: {
      context: "",
      domain: [],
      readonly: true,
      relation: "giscedata.polissa.tarifa",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Tarifa d'accés",
      type: "many2one",
      views: {},
    },
    tarifa_codi: {
      digits: [16, 2],
      string: "Codi Tarifa",
      type: "char",
      views: {},
    },
    tensio: {
      digits: [16, 2],
      readonly: 1,
      string: "Tensió (v)",
      type: "integer",
      views: {},
    },
    tensio_normalitzada: {
      context: "",
      domain: [],
      readonly: true,
      relation: "giscedata.tensions.tensio",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Tensió normalitzada",
      type: "many2one",
      views: {},
    },
    tg: {
      help: "Telegestió operativa amb o sense corba de càrrega (CCH)",
      readonly: true,
      selection: [
        ["1", "Operativa amb CCH"],
        ["2", "No operativa"],
        ["3", "Operativa Sense CCH"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Telegestió",
      type: "selection",
      views: {},
    },
    tipo_pago: {
      context: "",
      domain: [],
      readonly: true,
      relation: "payment.type",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Tipo de pago",
      type: "many2one",
      views: {},
    },
    tipus_vivenda: {
      readonly: true,
      selection: [
        ["habitual", "Habitual"],
        ["no_habitual", "No habitual"],
      ],
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [["readonly", false]],
        validar: [["readonly", false]],
      },
      string: "Tipus vivenda",
      type: "selection",
      views: {},
    },
    titular: {
      context: "",
      domain: [],
      readonly: true,
      relation: "res.partner",
      size: 40,
      states: {
        esborrany: [["readonly", false]],
        validar: [
          ["readonly", false],
          ["required", true],
        ],
      },
      string: "Titular",
      type: "many2one",
      views: {},
    },
    titular_nif: {
      digits: [16, 2],
      readonly: true,
      string: "NIF titular",
      type: "char",
      views: {},
    },
    trafo: {
      readonly: true,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", true],
        ],
        validar: [["readonly", false]],
      },
      string: "Trafo KVA",
      type: "float",
      views: {},
    },
    unpaid_invoices: {
      digits: [16, 2],
      readonly: 1,
      string: "Unpaid invoices",
      type: "integer",
      views: {},
    },
    user_id: {
      context: "",
      domain: [],
      relation: "res.users",
      size: 64,
      string: "Comercial",
      type: "many2one",
      views: {},
    },
    versio_primera_factura: {
      context: "",
      domain: [],
      help:
        "Estableix la versió de la llista de preus que s'utilitzarà per la primera facturació.",
      readonly: true,
      relation: "product.pricelist.version",
      size: 64,
      states: {
        esborrany: [["readonly", false]],
        modcontractual: [
          ["readonly", false],
          ["required", false],
        ],
        validar: [
          ["readonly", false],
          ["required", false],
        ],
      },
      string: "Versió primera facturació",
      type: "many2one",
      views: {},
    },
  },
  arch:
    '<form string="polisses">\n                    <group attrs="{\'invisible\': [(\'state\', \'!=\', \'tall\')]}" col="14">\n                        <group colspan="6"/>\n                        <group colspan="2" attrs="{\'invisible\': [(\'state\', \'!=\',\'tall\')]}" name="group_state_tall">\n                            <image name="gtk-cut"/>\n                            <label fill="1" string="&lt;b&gt;Atenció!&lt;/b&gt; aquest contracte està en estat Tall"/>\n                        </group>\n                        <group colspan="6"/>\n                    </group>\n                    <group attrs="{\'invisible\': [(\'state\', \'!=\', \'baixa\')]}" col="14">\n                        <group colspan="4"/>\n                        <group colspan="2" attrs="{\'invisible\': [(\'state\', \'!=\',\'baixa\')]}">\n                            <image name="gtk-stop"/>\n                            <label fill="1" string="&lt;b&gt;Atenció!&lt;/b&gt; aquest contracte està en estat Baixa"/>\n                        </group>\n                        <group colspan="8"/>\n                    </group>\n                    <group attrs="{\'invisible\': [(\'state\', \'!=\', \'facturacio\')]}" col="14">\n                        <group colspan="2"/>\n                        <group colspan="2"/>\n                        <group colspan="2"/>\n                        <group colspan="2">\n                            <image name="gtk-dialog-warning"/>\n                            <label fill="1" string="&lt;b&gt;Atenció!&lt;/b&gt; en aquests moments s\'està facturant. Actualitzi d\'aquí uns minuts."/>\n                        </group>\n                        <group colspan="2"/>\n                        <group colspan="2"/>\n                        <group colspan="2"/>\n                    </group>\n                <group colspan="8" col="8">\n                        <field name="pending_state" select="2"/>\n                        <field name="pending_amount" select="2"/>\n                        <field name="debt_amount" select="2"/>\n                        <field name="unpaid_invoices" select="2"/>\n                    </group>\n                <group colspan="6" col="6">\n                        <field name="process_id" select="2" attrs="{\'readonly\': [(\'bono_social_disponible\',\'=\', True)]}"/>\n                    </group>\n                <group string="General" colspan="6" col="6">\n                        <field name="name" attrs="{\'readonly\': [(\'name_auto\', \'=\', 1)], \'required\': [(\'name_auto\', \'!=\', 1)]}"/>\n                        <group colspan="2">\n                            <field name="name_auto" attrs="{\'readonly\': [(\'name\', \'!=\', False)]}"/>\n                            <field name="data_firma_contracte" select="2"/>\n                        </group>\n                        <group col="2" rowspan="4" name="renovacio">\n                            <field name="active" select="1"/>\n                            <field name="renovacio_auto" select="2" attrs="{\'readonly\': [(\'data_baixa\', \'!=\', False)]}"/>\n                            <field name="data_alta" select="2"/>\n                            <field name="data_baixa" select="2" on_change="onchange_data_baixa(data_baixa, context)" attrs="{\'required\': [(\'renovacio_auto\', \'=\', 0)], \'readonly\': [(\'renovacio_auto\', \'=\', 1)]}"/>\n                        </group>\n                        <field name="distribuidora" select="1"/>\n                    <field name="ref_dist" select="1"/>\n                <field name="titular" colspan="2" domain="[(\'customer\', \'=\', 1)]" on_change="onchange_titular(titular, pagador_sel, pagador, tipo_pago, notificacio, context)" select="1"/>\n                <field name="cnae" select="2"/>\n                    </group>\n                    <notebook colspan="6">\n                        <page string="General">\n                            <separator string="Cups" colspan="4"/>\n                            <field name="cups" select="1" size="25"/>\n                            <field name="cups_direccio" colspan="4" select="1"/>\n                            <field name="cups_cp" invisible="1" select="2"/>\n                            <field name="cups_poblacio" invisible="1" select="2"/>\n                            <separator string="Dades tècniques" colspan="4"/>\n                            <group col="2" colspan="2">\n                                <field name="contract_type" select="2"/>\n                                <group colspan="2" col="4" attrs="{\'invisible\':[(\'contract_type\', \'!=\', \'09\')]}">\n                        <field name="expected_consumption"/>\n                        <button string="Calcular" name="1366" states="esborrany,validar,modcontractual" type="action" readonly="0"/>\n                    </group>\n                <field name="tarifa" on_change="onchange_potencia(potencia, tarifa, context)" select="1"/>\n                                <group colspan="2" col="4">\n                                    <field name="potencia" select="1" on_change="onchange_potencia(potencia, tarifa, context)"/>\n                                    <button name="416" type="action" string="Normalitzar" context="{\'power\': potencia, \'tarifa_id\': tarifa, \'tensio_id\': tensio_normalitzada, \'model\': \'giscedata.polissa\', \'field\': \'potencia\'}" states="esborrany,validar,modcontractual" readonly="0"/>\n                                </group>\n                                <field name="tensio_normalitzada" select="2" on_change="onchange_tensio(tensio_normalitzada, tarifa, context)"/>\n                                <field name="tarifa_codi" invisible="1"/>\n                    <group colspan="4" attrs="{\'invisible\': [(\'tarifa_codi\',\'not in\',[\'3.1A\', \'3.1A LB\', \'6.1A\', \'6.1B\'])]}">\n                        <field name="lectura_en_baja" select="2"/>\n                        <group colspan="2" col="2" attrs="{\'invisible\': [(\'tarifa_codi\', \'!=\', \'3.1A LB\'),(\'lectura_en_baja\',\'=\',False)]}">\n                            <field name="trafo"/>\n                        </group>\n                    </group>\n                <field name="tensio"/>\n                                <field name="tg" select="2"/>\n                                <field name="condicions_generals_id" select="2"/>\n                <field name="autoconsumo" select="2"/>\n                                <field name="nocutoff"/>\n                            </group>\n                            <group col="2" colspan="2">\n                                <field name="potencies_periode" colspan="4" nolabel="1">\n                                    </field>\n                                <button name="generar_periodes_potencia" states="esborrany,validar,modcontractual" string="Generar periodes" type="object" context="{\'force_genpot\': True}"/>\n                            </group>\n                            <group col="4" colspan="4" attrs="{\'invisible\':[(\'persona_fisica\', \'=\', \'CI\')]}">\n                            <separator string="Altres dades" colspan="4"/>\n                            </group>\n                            <group col="4" colspan="2" attrs="{\'invisible\':[(\'persona_fisica\', \'=\', \'CI\')]}">\n                                <field name="tipus_vivenda" select="1"/>\n                                <field name="persona_fisica" invisible="1"/>\n                            </group>\n                        </page>\n                        <page string="Autoconsum" attrs="{\'invisible\':[(\'autoconsumo\',\'=\',\'00\')]}">\n                        <separator string="Informacio de l\'autoconsumo del CUPS associat" colspan="6"/>\n                        <group>\n                            <field name="autoconsum_id" attrs="{\'required\':[(\'autoconsumo\',\'!=\',\'00\'), (\'state\',\'in\',[\'validar\',\'modcontractual\'])]}" on_change="onchange_autoconsum_id(autoconsum_id)"/>\n                            <field name="ac_state"/>\n                            <group attrs="{\'invisible\':[(\'is_autoconsum_collectiu\',\'=\',False)]}">\n                                <field name="coef_repartiment" attrs="{\'required\':[(\'autoconsumo\',\'!=\',\'00\'), (\'is_autoconsum_collectiu\',\'=\',True), (\'state\',\'in\',[\'validar\',\'modcontractual\'])]}"/>\n                            </group>\n                            <field name="is_autoconsum_collectiu"/>\n                            <group attrs="{\'invisible\':[(\'is_autoconsum_collectiu\',\'!=\', True)]}">\n                                <field name="coef_repartiment" attrs="{\'required\':[(\'autoconsumo\',\'!=\',\'00\'), (\'is_autoconsum_collectiu\',\'=\',True), (\'state\',\'in\',[\'validar\',\'modcontractual\'])]}"/>\n                            </group>\n                        </group>\n                    </page>\n                <page string="Facturació"><separator string="Facturació" colspan="4"/>\n                    <field name="facturacio" select="1"/>\n                    <group col="2" colspan="2" string="Lot Facturació">\n                        <field name="lot_facturacio" select="1"/><field name="facturacio_suspesa" select="2" colspan="1"/>\n                \n                    </group>\n                    <group col="2" colspan="2">\n                        <field name="facturacio_potencia" select="2"/>\n                        <field name="property_unitat_potencia"/>\n                        <field name="deposit"/>\n                    </group>\n                    <group string="Dates últimes lectures facturades" col="2" colspan="2" rowspan="1">\n                        <field string="Real" name="data_ultima_lectura" select="2"/>\n                        <field string="Estimada" name="data_ultima_lectura_estimada"/><field name="refacturacio_pendent"/>\n                \n                    </group>\n                    <newline/>\n                    <separator string="Tarificació" colspan="4"/>\n                    <field name="llista_preu" select="1" domain="[(\'tarifes_atr_compatibles\', \'=\', tarifa), (\'type\', \'=\', \'sale\')]"/>\n                <!-- Dos dominis, la llista de preus que tingui i que la data_end sigui > now() -->\n                    <field name="versio_primera_factura" domain="[(\'pricelist_id\', \'=\', llista_preu), \'|\', (\'date_end\', \'&gt;\', data_alta), (\'date_end\', \'=\', False),]"/>\n                    <separator string="Pagament" colspan="4"/>\n                    <field name="payment_term" select="2"/>\n                    <field name="tipo_pago" on_change="onchange_tipo_pago(tipo_pago, pagador, context)" invisible="1"/>\n                    <field name="payment_mode_id" select="2" on_change="onchange_modo_pago(payment_mode_id, pagador, context)"/>\n                    <newline/>\n                <field name="bank" on_change="onchange_bank(propietari_bank, bank)" attrs="{\'readonly\': [(\'tipo_pago.code\', \'=\', \'RECIBO_CSB\')]}" domain="[(\'partner_id\', \'=\', pagador)]"/>\n                    <field name="propietari_bank"/>\n                <group col="4" colspan="4">\n                        <separator string="Facturació de distribuidora" colspan="4"/>\n                        <group colspan="2">\n                            <field name="facturacio_distri"/>\n                        </group>\n                    </group>\n                </page>\n                        <page string="Contactes">\n                            <separator string="Titular" colspan="4"/>\n                            <field name="titular_nif" select="1"/>\n                            <field name="representante_id" colspan="4"/>\n                <group colspan="4" col="6">\n                                <separator string="Privacitat" colspan="6"/>\n                                <field name="no_cessio_sips"/>\n                                <field name="no_cessio_sips_data"/><button string="Solicitar no cesión" type="action" icon="gtk-no" name="1622" colspan="1" readonly="0"/>\n                </group>\n                        <field name="user_id" invisible="1"/>\n                <newline/>\n             <separator colspan="4" string="Dades fiscals"/>\n                    <field name="pagador_sel" colspan="4" domain="[(\'customer\', \'=\', 1)]" on_change="onchange_pagador_sel(pagador_sel, titular, pagador, direccio_pagament, tipo_pago, notificacio, context)"/>\n                    <group colspan="4" col="4">\n                        <field name="pagador" on_change="onchange_altre_pagador(pagador, notificacio, context)" select="1"/>\n                        <field name="pagador_nif"/>\n                    </group>\n                    <field name="direccio_pagament" colspan="4" domain="[(\'partner_id\', \'=\', pagador), (\'type\', \'=\', \'invoice\')]" select="1" on_change="onchange_direccio_fiscal(direccio_pagament)"/>\n                    <field name="enviament"/>\n                    <group colspan="2" col="2" attrs="{\'invisible\': [(\'enviament\', \'=\', \'postal\')]}">\n                        <field name="pagador_email"/>\n                    </group>\n                <separator colspan="4" string="Notificació"/>\n                    <field name="notificacio" on_change="onchange_notificacio(notificacio, titular, pagador, altre_p, context)"/>\n                    <group attrs="{\'invisible\': [(\'notificacio\', \'!=\', \'altre_p\')]}" colspan="4">\n                        <field name="altre_p" colspan="4" on_change="onchange_altre_p(altre_p, context)"/>\n                    </group>\n                    <field name="direccio_notificacio" colspan="4" domain="[(\'partner_id\', \'=\', titular)]" select="2"/>\n                <group colspan="2" col="2" attrs="{\'invisible\': [(\'enviament\', \'=\', \'postal\')]}">\n                        <field name="notificacio_email"/>\n                    </group>\n                <group colspan="2">\n                        <field name="bono_social_disponible"/>\n                    </group>\n                </page>\n                        <page string="Comercial">\n                        <separator string="Dades Comercials" colspan="8"/>\n                        <group colspan="8" col="8" string="Comercial">\n                            <field name="comercial_id" colspan="4" select="1"/>\n                        <field name="comissio" domain="[(\'id\', \'in\', [])]" colspan="8"/>\n                 <button name="action_asignar_comissio_from_comercial" type="object" string="Asignar comissio del comercial" colspan="1"/>\n             <field name="codigo_promocional" select="2" colspan="8"/>\n                </group>\n                    </page>\n                <page string="Modificacions contr.">\n                            <field name="modcontractual_activa" search="1"/>\n                            <field name="modcontractuals_ids" colspan="4" nolabel="1"/>\n                        </page>\n                        <page string="Observacions">\n                            <label colspan="4" string="Les observacions que s\'escriguin aquí queden historitzades en les modificacions contractuals. Cada modificació contractual fa una còpia de les observacions actuals."/>\n                            <separator string="Observacions" colspan="4"/>\n                            <field name="observacions" nolabel="1" colspan="4" select="1"/>\n                            <separator string="Observacions impresses" colspan="4"/>\n                            <field name="print_observations" nolabel="1" colspan="4"/>\n                        </page>\n                        <page string="Perfils">\n                            <group colspan="2" col="4" string="Nivells d\'agregació">\n                                <separator string="Tensió" colspan="1"/>\n                                <separator string="Tarifa" colspan="1"/>\n                                <separator string="DH" colspan="1"/>\n                                <separator string="Tipus" colspan="1"/>\n                                <field name="agree_tensio" nolabel="1"/>\n                                <field name="agree_tarifa" nolabel="1"/>\n                                <field name="agree_dh" nolabel="1"/>\n                                <field name="agree_tipus" nolabel="1"/>\n                            </group>\n                        </page>\n                        <page string="Històric">\n                            <field name="log_ids" colspan="4" nolabel="1"/>\n                        </page>\n                        <page string="Documents rel.">\n                            <field name="related_attachments" colspan="4" nolabel="1"/>\n                        </page>\n                    <page string="Comptadors">\n                        <field name="comptador" invisible="1" select="1"/>\n                        <field name="comptadors" nolabel="1" colspan="4" context="{\'polissa_id\':active_id}"/>\n                    </page>\n                <page string="Butlletins">\n                        <field name="butlletins" colspan="4" nolabel="1" context="{\'polissa_id\': active_id, \'default_cups_id\': cups}"/>\n                    </page>\n                </notebook>\n                    <group colspan="2" col="4">\n                        <field name="state" select="1"/>\n                        <group col="15" colspan="2">\n                            <button name="esborrany" string="Esborrany" states="validar,pendent" readonly="0"/>\n                            <button name="cancelar" string="Cancel·lar" states="esborrany,activa" confirm="Està segur que vol cancel·lar aquesta pòlissa?" readonly="0"/>\n                            <button name="baixa" string="Baixa" states="activa,impagament,tall" readonly="0"/>\n                            <button name="impagament" string="Impagament" states="activa" confirm="Està segur que vol passar a estat d\'impagament aquesta pòlissa?" readonly="0"/>\n                            <button name="validar" string="Validar" states="esborrany" readonly="0"/>\n                            <button name="activar" string="Activar" states="impagament,tall,cancelada" readonly="0"/>\n                            <button name="to_draft" string="Passar a Esborrany" states="cancelada" readonly="0"/>\n                            <button name="contracte" string="Activar" states="validar" readonly="0"/>\n                            <button name="reactivar" string="Reactivar" states="baixa" confirm="Està segur que vol reactivar?" readonly="0"/>\n                            <button name="tallar" string="Tallar" states="impagament" confirm="Està segur que vol passar a estat de tall aquesta pòlissa?" readonly="0"/>\n                            <button name="modcontractual" string="Modificació contractual" states="activa" readonly="0"/>\n                            <button name="undo_modcontractual" string="Desfer mod. contractual" states="modcontractual" readonly="0"/>\n                            <button type="action" name="418" string="Crear nova modificació contractual" states="modcontractual" readonly="0"/>\n                        </group>\n                    </group>\n                </form>',
};
