const Lectura = {
  name: "Lectura",
  key: "lectura",
  fields: {
    ajust: {
      digits: [16, 3],
      string: "Ajust",
      type: "float",
      views: {},
    },
    ajust_exporta: {
      digits: [16, 3],
      string: "Ajust Exporta",
      type: "float",
      views: {},
    },
    comptador: {
      context: "",
      domain: [],
      relation: "giscedata.lectures.comptador",
      required: true,
      size: 64,
      string: "Comptador",
      type: "many2one",
      views: {},
    },
    consum: {
      digits: [16, 3],
      readonly: 1,
      string: "Consum",
      type: "float",
      views: {},
    },
    consum_autoconsumida: {
      digits: [16, 3],
      required: true,
      select: true,
      string: "Energia autoconsumida",
      type: "float",
      views: {},
    },
    consum_reactiva_capacitiva: {
      digits: [16, 3],
      required: true,
      select: true,
      string: "Reactiva capacitiva",
      type: "float",
      views: {},
    },
    generacio: {
      digits: [16, 3],
      readonly: 1,
      string: "Generació",
      type: "float",
      views: {},
    },
    incidencia_id: {
      context: "",
      domain: [],
      relation: "giscedata.lectures.incidencies.incidencia",
      size: 64,
      string: "Incidència",
      type: "many2one",
      views: {},
    },
    lectura: {
      required: true,
      select: true,
      string: "Lectura",
      type: "integer",
      views: {},
    },
    lectura_exporta: {
      required: true,
      select: true,
      string: "Lectura Exporta",
      type: "integer",
      views: {},
    },
    motiu_ajust: {
      selection: [
        ["01", "Verificación equipo de medida"],
        ["02", "Avería en contador"],
        ["03", "Avería en Trafo de Tensión"],
        ["04", "Avería en Trafo de intensidad"],
        ["05", "Desbordamiento del Registrador"],
        ["06", "Problemas en la sincronización del registrador"],
        ["07", "Pérdida de alimentación del registrador"],
        ["08", "Manipulación de equipos"],
        ["09", "Servicio Directo (sin EM)"],
        ["10", "Punto de medida inaccesible"],
        ["11", "Punto de medida ilocalizable"],
        ["99", "Otros"],
        ["98", "Autoconsumo"],
        ["97", "Transformacion a TD"],
      ],
      string: "Motiu Ajust",
      type: "selection",
      views: {},
    },
    name: {
      required: true,
      select: true,
      string: "Data",
      type: "date",
      views: {},
    },
    observacions: {
      string: "Observacions",
      type: "text",
      views: {},
    },
    origen_comer_id: {
      context: "",
      domain: [],
      relation: "giscedata.lectures.origen_comer",
      required: true,
      size: 64,
      string: "Orígen Comer.",
      type: "many2one",
      views: {},
    },
    origen_id: {
      context: "",
      domain: [],
      relation: "giscedata.lectures.origen",
      required: true,
      size: 64,
      string: "Orígen",
      type: "many2one",
      views: {},
    },
    periode: {
      context: "",
      domain: [],
      relation: "giscedata.polissa.tarifa.periodes",
      required: true,
      size: 64,
      string: "Periode",
      type: "many2one",
      views: {},
    },
    tipus: {
      required: true,
      select: 1,
      selection: [
        ["A", "Activa"],
        ["R", "Reactiva"],
        ["RC", "Reactiva Capacitiva"],
      ],
      string: "Tipus",
      type: "selection",
      views: {},
    },
  },
  data: [
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [15, "32323232"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 25,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-09-30",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [5, "Visual"],
      periode: [1, "2.0A (P1)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [15, "32323232"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 21,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-08-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [5, "Visual"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [15, "32323232"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 22,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-08-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [5, "Visual"],
      periode: [1, "2.0A (P1)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [13, "1234567898"],
      consum: 250.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 11,
      incidencia_id: false,
      lectura: 400,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [13, "1234567898"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 12,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [1, "2.0A (P1)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [14, "987654321"],
      consum: 100.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 17,
      incidencia_id: false,
      lectura: 200,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [5, "2.0DHA (P1)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [14, "987654321"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 18,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [5, "2.0DHA (P1)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [14, "987654321"],
      consum: 50.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 19,
      incidencia_id: false,
      lectura: 50,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [6, "2.0DHA (P2)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [14, "987654321"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 20,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [6, "2.0DHA (P2)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [14, "987654321"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 13,
      incidencia_id: false,
      lectura: 100,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-08",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [5, "2.0DHA (P1)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [14, "987654321"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 14,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-08",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [5, "2.0DHA (P1)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [14, "987654321"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 15,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-08",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [6, "2.0DHA (P2)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [14, "987654321"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 16,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-07-08",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [6, "2.0DHA (P2)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [13, "1234567898"],
      consum: 150.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 9,
      incidencia_id: false,
      lectura: 150,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-06-30",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [13, "1234567898"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 10,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-06-30",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [1, "2.0A (P1)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [13, "1234567898"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 7,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-05-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [13, "1234567898"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 8,
      incidencia_id: false,
      lectura: 0,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2020-05-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [11, "Telegestió"],
      periode: [1, "2.0A (P1)"],
      tipus: "R",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [1, "B63011077"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 6,
      incidencia_id: [1, "A100 - CONTADOR SIN CONTRATO, ERROR ADMINISTRATIVO"],
      lectura: 17,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2017-01-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [1, "Telemesura"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [1, "B63011077"],
      consum: 1.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 5,
      incidencia_id: false,
      lectura: 17,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2016-12-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [1, "Telemesura"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 15.0,
      ajust_exporta: 0.0,
      comptador: [1, "B63011077"],
      consum: 15.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 3,
      incidencia_id: false,
      lectura: 16,
      lectura_exporta: 0,
      motiu_ajust: "01",
      name: "2016-04-04",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [1, "Telemesura"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 3.0,
      ajust_exporta: 0.0,
      comptador: [1, "B63011077"],
      consum: 3.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 2,
      incidencia_id: false,
      lectura: 16,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2016-03-03",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [1, "Telemesura"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 0.0,
      ajust_exporta: 0.0,
      comptador: [1, "B63011077"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 1,
      incidencia_id: false,
      lectura: 16,
      lectura_exporta: 0,
      motiu_ajust: false,
      name: "2016-02-02",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [1, "Telemesura"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
    {
      ajust: 15.0,
      ajust_exporta: 0.0,
      comptador: [3, "42553686"],
      consum: 0.0,
      consum_autoconsumida: 0.0,
      consum_reactiva_capacitiva: 0.0,
      generacio: 0.0,
      id: 4,
      incidencia_id: false,
      lectura: 1,
      lectura_exporta: 0,
      motiu_ajust: "01",
      name: "2015-10-31",
      observacions: false,
      origen_comer_id: [3, "Entrada manual"],
      origen_id: [1, "Telemesura"],
      periode: [1, "2.0A (P1)"],
      tipus: "A",
    },
  ],
};

export default Lectura;
