name: Update dependent projects (v2)

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  LIBRARY_NAME: "gisce/ooui"

jobs:
  update-dependents:
    if: github.event.release.prerelease == false && contains(github.event.release.tag_name, 'v2')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: "gisce/react-ooui"
            branch: "v2"
    steps:
      - name: Call Reusable Workflow for each project
        uses: gisce/create-update-version-pr@v0.0.5
        with:
          dependentProject: ${{ matrix.project }}
          tagName: ${{ github.event.release.tag_name }}
          dependentProjectBranch: ${{ matrix.branch }}
          libraryName: ${{ env.LIBRARY_NAME }}
          githubToken: ${{ secrets.GH_PAT }}
